spring.application.name=api-gateway

server.port=8000

spring.datasource.url=jdbc:postgresql://localhost:5433/aegis_db
spring.datasource.username=aegis
spring.datasource.password=aegispassword
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
