package com.aegisfi.api_gateway.service;

import com.aegisfi.api_gateway.model.Transaction;
import org.springframework.stereotype.Service;
import lombok.Data;
import lombok.Builder;

import java.util.List;
import java.util.Set;
import java.util.stream.Collectors;

@Service
public class DecisionEngine {

    @Data
    @Builder
    public static class DecisionResult {
        private String recommendedAction;
        private String reason;
        private Double projectedFraudLoss;
        private String customerFriction;
        private Double revenueImpact;
        private String complianceStatus;
        private String memorySimilarity;
        private Integer sharedDeviceCount;
    }

    public DecisionResult evaluate(Transaction tx, List<Transaction> allTransactions, List<Transaction> customerHistory) {
        int riskScore = tx.getRiskScore() != null ? tx.getRiskScore() : 0;
        double amount = tx.getAmount() != null ? tx.getAmount() : 0.0;
        String device = tx.getDevice();
        String country = tx.getCountry();
        String customer = tx.getCustomer();

        // 1. Knowledge Graph (Shared Device Count)
        int sharedDeviceCount = 0;
        if (device != null && !device.trim().isEmpty()) {
            Set<String> otherCustomers = allTransactions.stream()
                    .filter(t -> device.equalsIgnoreCase(t.getDevice()) && t.getCustomer() != null && !t.getCustomer().equalsIgnoreCase(customer))
                    .map(Transaction::getCustomer)
                    .collect(Collectors.toSet());
            sharedDeviceCount = otherCustomers.size();
        }

        // 2. Memory Cortex (Similarity to past customer transactions)
        double memorySimPercent = 95.0;
        if (!customerHistory.isEmpty()) {
            double avgAmount = customerHistory.stream()
                    .mapToDouble(Transaction::getAmount)
                    .average()
                    .orElse(amount);
            
            double ratio = Math.max(amount, avgAmount) / Math.min(amount, avgAmount);
            if (ratio > 10.0) {
                memorySimPercent = 35.0; // Heavy volume outlier
            } else if (ratio > 3.0) {
                memorySimPercent = 65.0; // Moderate outlier
            } else {
                memorySimPercent = 95.0 - (ratio - 1.0) * 10.0;
            }
        }
        String memorySimStr = String.format("%.1f%%", Math.max(5.0, Math.min(100.0, memorySimPercent)));

        // 3. Compliance evaluation
        String complianceStatus = "GREEN";
        boolean isSanctionedCountry = "KP".equalsIgnoreCase(country) || "IR".equalsIgnoreCase(country) || "SY".equalsIgnoreCase(country);
        if (isSanctionedCountry) {
            complianceStatus = "RED (Sanction Block)";
        } else if (amount > 10000.0) {
            complianceStatus = "AMBER (High-value AML check)";
        }

        // 4. Decision logic (Recommended Action determination)
        String recommendedAction = "APPROVE";
        String reason = "All anomaly checks cleared successfully.";
        double fraudLossRate = riskScore / 100.0;

        if ("RED (Sanction Block)".equalsIgnoreCase(complianceStatus)) {
            recommendedAction = "FREEZE";
            reason = "Sanctioned destination region violation detected.";
        } else if (riskScore >= 80) {
            recommendedAction = "FREEZE";
            reason = "High anomaly risk score generated by Sentinel agent.";
        } else if (sharedDeviceCount >= 2) {
            recommendedAction = "FREEZE";
            reason = "Knowledge Graph detected active fraud ring (shared device limit exceeded).";
        } else if (riskScore >= 45 || sharedDeviceCount > 0 || "AMBER (High-value AML check)".equalsIgnoreCase(complianceStatus) || memorySimPercent < 50.0) {
            recommendedAction = "OTP_CHALLENGE";
            if (sharedDeviceCount > 0) {
                reason = "Shared hardware signature detected on other client accounts.";
            } else if (memorySimPercent < 50.0) {
                reason = "Outlier transaction volume compared to historic spending DNA.";
            } else if ("AMBER (High-value AML check)".equalsIgnoreCase(complianceStatus)) {
                reason = "Transaction amount exceeds standard AML reporting threshold.";
            } else {
                reason = "Elevated Sentinel risk vector detected.";
            }
        }

        // 5. Projected metrics based on recommended action
        double projectedFraudLoss = 0.0;
        String customerFriction = "Low";
        double revenueImpact = amount * 0.0025; // 0.25% merchant fee revenue

        if ("APPROVE".equalsIgnoreCase(recommendedAction)) {
            projectedFraudLoss = amount * fraudLossRate;
            customerFriction = "Low";
        } else if ("OTP_CHALLENGE".equalsIgnoreCase(recommendedAction)) {
            projectedFraudLoss = amount * fraudLossRate * 0.05; // OTP blocks 95% of fraud
            customerFriction = "Medium/High";
            revenueImpact -= 1.10; // cost of verification SMS/OTP
        } else { // FREEZE
            projectedFraudLoss = 0.0;
            customerFriction = "Critical";
            revenueImpact = -amount * 0.025; // profile locking friction impact
        }

        return DecisionResult.builder()
                .recommendedAction(recommendedAction)
                .reason(reason)
                .projectedFraudLoss(projectedFraudLoss)
                .customerFriction(customerFriction)
                .revenueImpact(revenueImpact)
                .complianceStatus(complianceStatus)
                .memorySimilarity(memorySimStr)
                .sharedDeviceCount(sharedDeviceCount)
                .build();
    }
}
